version: "3.8"

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iset_chatbot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
      - ./web/static/images:/app/web/static/images
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=Africa/Tunis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: iset_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/static:/usr/share/nginx/html/static:ro
    depends_on:
      - chatbot
    networks:
      - chatbot_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  chatbot_network:
    driver: bridge

volumes:
  data:
  logs:
  static_images:
